ProjectDekerfsteve/Controllers/VraagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ProjectDekerfsteve;
using ProjectDekerfsteve.Resources;

namespace ProjectDekerfsteve.Controllers
{
    public class VraagController : Controller
    {
        private INFO_c1035462Entities db = new INFO_c1035462Entities();

        [Authorize (Roles = "Admin, Organisator") ]
        public ActionResult Index()
        {
            int res;
            if (User.IsInRole("Admin"))
            {
                res = 1;
            }
            else
            {
                res = 0;
            }
            return View(db.Proj_Vragen.Where(x => x.type == res).ToList());
        }

        // GET: Vraag/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vragen vragen = db.Proj_Vragen.Find(id);
            if (vragen == null)
            {
                return HttpNotFound();
            }
            return View(vragen);
        }

        // GET: Vraag/Create
        public ActionResult Create()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = Teksten.Question, Value = "0" });
            items.Add(new SelectListItem { Text = Teksten.Remark, Value = "1" });
            ViewBag.type = items;
            return View();
        }

        // POST: Vraag/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,naam,voornaam,adres,gemeente,type,content,date")] Vragen vragen)
        {
            if (ModelState.IsValid)
            {
                db.Proj_Vragen.Add(vragen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vragen);
        }

        // GET: Vraag/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vragen vragen = db.Proj_Vragen.Find(id);
            if (vragen == null)
            {
                return HttpNotFound();
            }
            return View(vragen);
        }

        // POST: Vraag/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,naam,voornaam,adres,gemeente,type,content,date")] Vragen vragen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vragen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vragen);
        }

        // GET: Vraag/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vragen vragen = db.Proj_Vragen.Find(id);
            if (vragen == null)
            {
                return HttpNotFound();
            }
            return View(vragen);
        }

        // POST: Vraag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vragen vragen = db.Proj_Vragen.Find(id);
            db.Proj_Vragen.Remove(vragen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectDekerfsteve/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index" class="nav navbar-brand" ><img src="~/pics/2017573-664645_20121106_001.jpg" width="30" height="21" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink(Teksten.Contact, "Contact", "Home")</li>
                    @if (User.IsInRole("Admin") || User.IsInRole("Organisator"))
                    {
                        <li>@Html.ActionLink(Teksten.Overview, "Index", "Vraag")</li>
                    }
                    <li>@Html.ActionLink(Teksten.events, "Index", "evenement")</li>
                    <li>@Html.ActionLink(Teksten.change, "Extra", "Account")</li>
                    <li>@Html.ActionLink(Teksten.French, "Change", "Language", new {LanguageAbbrevation = "fr"}, new {})</li>
                    <li>@Html.ActionLink(Teksten.Dutch, "Change", "Language", new {LanguageAbbrevation = "nl"}, new {})</li>
                 
                </ul>
                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Karting Club "On The Edge"</p>
        </footer>
    </div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryui")
@RenderSection("scripts", required: false)
</body>
</html>

ProjectDekerfsteve/Views/Shared/_Subscribe.cshtml
@model String
@{
    Model.ToString();   
}